language: ruby

rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
env:
  matrix:
    - INTEGRATE_WITH=default
    - INTEGRATE_WITH=1.8.7
  global:
    - secure: "UE5QlcvsNEEIiaFVBThh9LFW3LyQG8endi10y1kislgdlVrkpx/b/REU0wwz\nLf1aPGMtKCWbRqBZk0zg8JYTQoig/2wXnct5IJuabOrtgcoWZl/pxGr/0U5A\n5/v0pEq1i3FtXBbOe4Oe2vQuJzhs/WrUXO6gGHsncwQsAreqJtw="
    - secure: "IerTwFN0kvQ8zEXxoZJ/NQjwyRzSxh9HbDdr1IljNLyEgDIfx5i57ufemwlH\nVujsITuwg1Ut6b7OLfXFTmbdGHR21XhI3TMBoO34bLuChNlKFQaSkibVSXqe\nr1cTmnbsmVYM4IMImiS0c15WVpVZTYesZTB+P5EsIeQdFJ+j0cw="
    - secure: "nZQ4n2D+pzOgWz9Rb75L0NQoKvHOOkms+EpRUlbpq/saSN1pITIpbwGtlbpm\nFGGZbilQxfmdgkp1Wg+3/BmRjgWbn7vjrmudZ5Y137uebmtFhI46/wcjaSTf\n3LBbxkxIQMnzNxGE6PgZgJBrow2pSJ6+ZGI6bk50n+PKQc0kVKY="
    - secure: "t/u/i4F02vNym2kwopei2UDWL7FmLkn5t05Qya2kqObENGHHf3vv4OHIB6Ok\nZguSrMkf4BP9mx9GeFbga1vEUo/L88tls7L3wsqdLEwzevRaqlqOcUbVP/jL\nh4MZ/TJ/zpfDY1ddm3jB7qI0GF1UcFppdxO16A33JgDkyqjL1cw="
    - secure: "T0wMEmJjya+D+Qvx4hZfHwaBXBYSeQFo4qSSwKsv2UkLnDmi2R+Wmv+mCMUe\noKzXhYEeTAQ7QXIMGU2pQKsHMFYrECsNxS9Y7P7XHWeo7MOwu4zRfcOhkCMk\ndmkR92TEM4Np3hVVDFz3SzivwxV60Txa5b5JO2IvnhmAqvj9SLM="
    - secure: "cjF0yCIHb+JvolUkUtJXwjgD+4pub5nJ5mDP1meoC3f6NRMlL8Tm8a4+k3US\nujEqn2GUXKZvWFmcO/PSNIZ50xNuSFnArPjQ0b1RLpxB7+UJTix5b07of4pr\nntXG0zvMjuocNxyEt/skGbjbZk8/sVyfCVhFcmc3sYYdUinJXks="
    - secure: "QIR+zEq8nlFtHbWcp4r0MJ0gibijNB8y81vvf0FlnsY/oCITRevxgIr7D7i1\nzVGoVie0NiguCmXHBVpKIZXnd2OKBcFOM2T9sf5vEeQtF+gjGDcLL2ZPRxOT\nbLkjkg2MWMiEX4HeLd4f9aZEZSCHFvn9PfqANPZGPm767B4gMak="

before_script: ./script/setup_187

matrix:
  exclude:
    - rvm: 1.8.7
      env: INTEGRATE_WITH=1.8.7
    - rvm: 1.9.2
      env: INTEGRATE_WITH=1.8.7
